# Generated by Django 6.0.7 on 2026-07-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط (Slug)')),
                ('content', models.TextField(verbose_name='محتوى المقال')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/%d/', verbose_name='صورة المقال')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='وصف لمحركات البحث (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
