# Generated by Django 6.0.7 on 2026-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_comment_options_comment_active_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Unknown', max_length=500),
        ),
    ]
