# Generated by Django 6.0.7 on 2026-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='غير معروف', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='غير معروف', max_length=50),
        ),
    ]
