# Generated by Django 6.0.7 on 2026-07-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_comment_alter_comment_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'تعليق المقال', 'verbose_name_plural': 'تعليقات المقالات'},
        ),
    ]
