# Generated by Django 6.0.7 on 2026-07-23 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الحلقة')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط (Slug)')),
                ('description', models.TextField(verbose_name='وصف الحلقة')),
                ('audio_file', models.FileField(upload_to='podcasts/audio/%Y/%m/%d/', verbose_name='الملف الصوتي')),
                ('image', models.ImageField(upload_to='podcasts/images/%Y/%m/%d/', verbose_name='صورة الغلاف')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشورة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مقدم الحلقة')),
            ],
            options={
                'verbose_name': 'حلقة بودكاست',
                'verbose_name_plural': 'حلقات البودكاست',
                'ordering': ['-created_at'],
            },
        ),
    ]
