# Generated by Django 6.0.7 on 2026-07-25 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='author',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='image',
        ),
        migrations.AddField(
            model_name='podcast',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صوت خارجي (اختياري)'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='podcasts/covers/%Y/%m/%d/', verbose_name='غلاف الحلقة (Cover)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.CharField(blank=True, help_text='مثال: 45:20', max_length=20, null=True, verbose_name='مدة الحلقة'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقدم / المضيف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='وصف لمحركات البحث (SEO)'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/audio/%Y/%m/%d/', verbose_name='ملف الصوت (MP3/WAV)'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(verbose_name='وصف الحلقة (Show Notes)'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='أنشر؟'),
        ),
        migrations.CreateModel(
            name='PodcastComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='غير معروف', max_length=50, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('comment', models.TextField(default='غير معروف', max_length=500, verbose_name='التعليق')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='podcasts.podcast')),
            ],
            options={
                'verbose_name': 'تعليق بودكاست',
                'verbose_name_plural': 'تعليقات البودكاست',
                'ordering': ['-comment_date'],
            },
        ),
    ]
